const FETCH_MOVIES = {
  LOAD: "FETCH_MOVIES_LOAD",
  SUCCESS: "FETCH_MOVIES_SUCCESS",
  FAIL: "FETCH_MOVIES_FAIL",
};

const FETCH_MORE = {
  LOAD: "FETCH_MORE_LOAD",
  SUCCESS: "FETCH_MORE_SUCCESS",
};

export { FETCH_MOVIES, FETCH_MORE };
