const FETCH_MOVIES = {
  LOAD: "FETCH_MOVIES_LOAD",
  SUCCESS: "FETCH_MOVIES_SUCCESS",
  FAIL: "FETCH_MOVIES_FAIL",
  SEARCH: "FETCH_MOVIES_SEARCH",
};

const FETCH_MORE = {
  LOAD: "FETCH_MORE_LOAD",
  SUCCESS: "FETCH_MORE_SUCCESS",
};

const FAVOURITES = {
  ADD: "FAVOURITES_ADD",
  REMOVE: "FAVOURITES_REMOVE",
};

const OTHER = {
  TOGGLE_SIDEDRAWER: "TOGGLE_SIDEDRAWER",
};

export { FETCH_MOVIES, FETCH_MORE, FAVOURITES, OTHER };
